[tool.poetry]
authors     = []
description = ""
name        = "dyn-demo"
version     = "0.1.0"

[tool.poetry.dependencies]
lib-a  = { path = "./lib-a", develop = true }
python = "^3.10"

[build-system]
build-backend = "poetry.core.masonry.api"
requires      = ["poetry-core"]
