on:
  - push
  - pull_request

name: Main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: |
          pip install --pre poetry==1.2.0a2
          poetry install
          poetry run pre-commit run --all-files --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
        poetry-version:
          - '1.2.0a2'
        install-method:
          - pip
          - script
    env:
      POETRY_VER: ${{ matrix.poetry-version }}
      INSTALL_METHOD: ${{ matrix.install-method }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -o ./install-poetry.py
          if [ "$INSTALL_METHOD" = "pip" ]; then pip install --pre poetry==${POETRY_VER}; fi
          if [ "$INSTALL_METHOD" = "script" ]; then python ./install-poetry.py --version ${POETRY_VER} --yes; fi
          poetry install
          poetry run pytest --verbose
          ./tests/integration.sh
